Genre.create(name: "Hiphop")
Genre.create(name: "Breakin")
Genre.create(name: "Lock")
Genre.create(name: "Pop")
Genre.create(name: "House")
Genre.create(name: "Krump")
Genre.create(name: "Jazz")
Genre.create(name: "Freestlye")
Genre.create(name: "etc.")

